-- 1) Upsert frameworks
INSERT INTO public.frameworks (id, name, version, description, categories)
VALUES
  ('csa-star', 'CSA STAR', '4.0', 'Cloud Security Alliance Security Trust Assurance and Risk - Cloud security certification program', ARRAY['Cloud Security Controls', 'Risk Management', 'Security Operations', 'Data Security']),
  ('iso-27017', 'ISO 27017', '2015', 'Code of practice for information security controls for cloud services', ARRAY['Cloud Service Provider Controls', 'Cloud Customer Controls', 'Shared Controls']),
  ('iso-27018', 'ISO 27018', '2019', 'Code of practice for protection of personally identifiable information (PII) in public clouds', ARRAY['Consent and Choice', 'Purpose Legitimacy', 'Data Minimization', 'Use Limitation']),
  ('iso-27001', 'ISO/IEC 27001', '2022', 'Information Security Management System Requirements', ARRAY['Information Security Policies', 'Organization of Information Security', 'Human Resource Security', 'Asset Management', 'Access Control', 'Cryptography', 'Physical and Environmental Security', 'Operations Security', 'Communications Security', 'System Acquisition, Development and Maintenance', 'Supplier Relationships', 'Information Security Incident Management', 'Business Continuity Management', 'Compliance']),
  ('iso27001-2022', 'ISO/IEC 27001', '2022', 'Information Security Management System Requirements', ARRAY['Information Security Policies', 'Organization of Information Security', 'Human Resource Security', 'Asset Management', 'Access Control', 'Cryptography', 'Physical and Environmental Security', 'Operations Security', 'Communications Security', 'System Acquisition, Development and Maintenance', 'Supplier Relationships', 'Information Security Incident Management', 'Business Continuity Management', 'Compliance']),
  ('gdpr', 'GDPR', '2016/679', 'General Data Protection Regulation - EU data protection and privacy framework', ARRAY['Data Protection Principles', 'Data Subject Rights', 'Controller and Processor Obligations', 'Security Requirements', 'Data Transfer Requirements']),
  ('hipaa', 'HIPAA', '2013', 'Health Insurance Portability and Accountability Act - US healthcare data privacy and security standards', ARRAY['Privacy Rule', 'Security Rule', 'Breach Notification Rule', 'Enforcement Rule']),
  ('iso-42001', 'ISO 42001', '2023', 'Artificial Intelligence Management System (AIMS) - Requirements and guidance for AI governance', ARRAY['AI Governance', 'Risk Management', 'Ethical Considerations', 'Transparency Requirements']),
  ('soc2', 'SOC 2', '2017', 'Service Organization Control 2 - Trust Services Criteria for security, availability, processing integrity, confidentiality, and privacy', ARRAY['Security', 'Availability', 'Processing Integrity', 'Confidentiality', 'Privacy']),
  ('nist-ai-rmf', 'NIST AI RMF', '1.0', 'NIST Artificial Intelligence Risk Management Framework - Guidelines for managing risks in AI systems', ARRAY['Govern', 'Map', 'Measure', 'Manage']),
  ('nist-800-53', 'NIST 800-53', 'Rev. 5', 'Security and Privacy Controls for Information Systems and Organizations', ARRAY['Access Control', 'Awareness and Training', 'Audit and Accountability', 'Security Assessment and Authorization', 'Configuration Management', 'Contingency Planning', 'Identification and Authentication', 'Incident Response', 'Maintenance', 'Media Protection', 'Physical and Environmental Protection', 'Planning', 'Program Management', 'Personnel Security', 'Risk Assessment', 'System and Services Acquisition', 'System and Communications Protection', 'System and Information Integrity', 'Supply Chain Risk Management']),
  ('pci-dss', 'PCI DSS', '4.0', 'Payment Card Industry Data Security Standard - Requirements and security assessment procedures', ARRAY['Build and Maintain a Secure Network', 'Protect Cardholder Data', 'Maintain Vulnerability Management Program', 'Implement Strong Access Control Measures', 'Regularly Monitor and Test Networks', 'Maintain Information Security Policy'])
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      version = EXCLUDED.version,
      description = EXCLUDED.description,
      categories = EXCLUDED.categories;

-- 2) Upsert controls
INSERT INTO public.controls (id, framework_id, name, description)
VALUES
  ('AIS', 'csa-star', 'Application & Interface Security', 'Controls for application security and interfaces'),
  ('AAC', 'csa-star', 'Audit Assurance & Compliance', 'Controls for audit planning and compliance'),
  ('BCR', 'csa-star', 'Business Continuity Management', 'Controls for business continuity and operational resilience'),
  ('CSP', 'iso-27017', 'Cloud Service Provider Controls', 'Controls specific to cloud service providers'),
  ('CUC', 'iso-27017', 'Cloud Customer Controls', 'Controls specific to cloud service customers'),
  ('SHC', 'iso-27017', 'Shared Controls', 'Controls shared between provider and customer'),
  ('CON', 'iso-27018', 'Consent and Choice', 'Controls for obtaining and managing consent'),
  ('PUR', 'iso-27018', 'Purpose Legitimacy', 'Controls for ensuring legitimate processing purposes'),
  ('MIN', 'iso-27018', 'Data Minimization', 'Controls for minimizing PII processing'),
  ('A.5', 'iso-27001', 'A.5 Information Security Policies', 'Management direction for information security'),
  ('A.6', 'iso-27001', 'A.6 Organization of Information Security', 'Internal organization and mobile devices/teleworking'),
  ('A.7', 'iso-27001', 'A.7 Human Resource Security', 'Security aspects for employees and contractors'),
  ('A.8', 'iso-27001', 'A.8 Asset Management', 'Identifying organizational assets and defining protection responsibilities'),
  ('A.9', 'iso-27001', 'A.9 Access Control', 'Business requirements and user access management'),
  ('A.10', 'iso-27001', 'A.10 Cryptography', 'Cryptographic controls'),
  ('A.11', 'iso-27001', 'A.11 Physical and Environmental Security', 'Secure areas and equipment'),
  ('A.12', 'iso-27001', 'A.12 Operations Security', 'Operational procedures and responsibilities'),
  ('A.13', 'iso-27001', 'A.13 Communications Security', 'Network security management and information transfer'),
  ('A.14', 'iso-27001', 'A.14 System Acquisition, Development and Maintenance', 'Security requirements of information systems'),
  ('A.15', 'iso-27001', 'A.15 Supplier Relationships', 'Information security in supplier relationships'),
  ('A.16', 'iso-27001', 'A.16 Information Security Incident Management', 'Management of information security incidents'),
  ('A.17', 'iso-27001', 'A.17 Information Security Aspects of Business Continuity Management', 'Business continuity and assessment'),
  ('A.18', 'iso-27001', 'A.18 Compliance', 'Compliance with legal and contractual requirements'),
  ('A.5', 'iso27001-2022', 'A.5 Information Security Policies', 'Management direction for information security'),
  ('A.6', 'iso27001-2022', 'A.6 Organization of Information Security', 'Internal organization and mobile devices/teleworking'),
  ('A.7', 'iso27001-2022', 'A.7 Human Resource Security', 'Security aspects for employees and contractors'),
  ('A.8', 'iso27001-2022', 'A.8 Asset Management', 'Identifying organizational assets and defining protection responsibilities'),
  ('A.9', 'iso27001-2022', 'A.9 Access Control', 'Business requirements and user access management'),
  ('A.10', 'iso27001-2022', 'A.10 Cryptography', 'Cryptographic controls'),
  ('A.11', 'iso27001-2022', 'A.11 Physical and Environmental Security', 'Secure areas and equipment'),
  ('A.12', 'iso27001-2022', 'A.12 Operations Security', 'Operational procedures and responsibilities'),
  ('A.13', 'iso27001-2022', 'A.13 Communications Security', 'Network security management and information transfer'),
  ('A.14', 'iso27001-2022', 'A.14 System Acquisition, Development and Maintenance', 'Security requirements of information systems'),
  ('A.15', 'iso27001-2022', 'A.15 Supplier Relationships', 'Information security in supplier relationships'),
  ('A.16', 'iso27001-2022', 'A.16 Information Security Incident Management', 'Management of information security incidents'),
  ('A.17', 'iso27001-2022', 'A.17 Information Security Aspects of Business Continuity Management', 'Business continuity and assessment'),
  ('A.18', 'iso27001-2022', 'A.18 Compliance', 'Compliance with legal and contractual requirements'),
  ('CH2', 'gdpr', 'Chapter II - Principles', 'Core principles relating to processing of personal data'),
  ('CH3', 'gdpr', 'Chapter III - Data Subject Rights', 'Rights of individuals regarding their personal data'),
  ('CH4', 'gdpr', 'Chapter IV - Controller and Processor', 'Obligations of data controllers and processors'),
  ('PRV', 'hipaa', 'Privacy Rule', 'Standards for protection and use of protected health information (PHI)'),
  ('SEC', 'hipaa', 'Security Rule', 'Administrative, physical, and technical safeguards for electronic PHI'),
  ('BRE', 'hipaa', 'Breach Notification', 'Requirements for notification of breaches of unsecured PHI'),
  ('ENF', 'hipaa', 'Enforcement Rule', 'Compliance and investigation processes, and penalties for violations'),
  ('GOV', 'iso-42001', 'AI Governance', 'Organizational structure and responsibilities for AI systems'),
  ('RISK', 'iso-42001', 'Risk Management', 'Identification and management of AI-related risks'),
  ('ETH', 'iso-42001', 'Ethical Considerations', 'Ethical principles and requirements for AI systems'),
  ('TRA', 'iso-42001', 'Transparency Requirements', 'Requirements for AI system transparency and explainability'),
  ('DEV', 'iso-42001', 'Development and Testing', 'Requirements for AI system development and testing'),
  ('CC', 'soc2', 'Common Criteria (Security)', 'Security controls applicable to all Trust Services Categories'),
  ('A', 'soc2', 'Availability', 'System availability and performance'),
  ('PI', 'soc2', 'Processing Integrity', 'System processing is complete, valid, accurate, timely, and authorized'),
  ('C', 'soc2', 'Confidentiality', 'Information designated as confidential is protected'),
  ('P', 'soc2', 'Privacy', 'Personal information is collected, used, retained, disclosed, and disposed of properly'),
  ('GOV', 'nist-ai-rmf', 'Govern', 'Establishing governance structures and processes for AI risk management'),
  ('MAP', 'nist-ai-rmf', 'Map', 'Identifying and tracking context, capabilities, and risks of AI systems'),
  ('MEA', 'nist-ai-rmf', 'Measure', 'Analyzing, assessing, and tracking AI risks'),
  ('MAN', 'nist-ai-rmf', 'Manage', 'Prioritizing, responding to, and communicating about AI risks'),
  ('AC', 'nist-800-53', 'Access Control', 'Access Control family of controls'),
  ('AT', 'nist-800-53', 'Awareness and Training', 'Security awareness and training controls'),
  ('AU', 'nist-800-53', 'Audit and Accountability', 'Audit and accountability controls'),
  ('CM', 'nist-800-53', 'Configuration Management', 'Configuration management controls for information systems'),
  ('CP', 'nist-800-53', 'Contingency Planning', 'Controls to ensure system availability and recovery'),
  ('REQ1', 'pci-dss', 'Install and maintain network security controls', 'Network security controls (NSCs) are installed and maintained to protect the cardholder data environment'),
  ('REQ2', 'pci-dss', 'Apply secure configurations', 'Apply secure configurations to all system components'),
  ('REQ3', 'pci-dss', 'Protect stored account data', 'Protect stored cardholder data'),
  ('REQ4', 'pci-dss', 'Protect cardholder data with encryption', 'Encrypt transmission of cardholder data across open, public networks'),
  ('REQ5', 'pci-dss', 'Protect against malware', 'Protect all systems against malware and regularly update anti-virus software or programs'),
  ('REQ6', 'pci-dss', 'Develop and maintain secure systems', 'Develop and maintain secure systems and applications')
ON CONFLICT (id) DO UPDATE
  SET framework_id = EXCLUDED.framework_id,
      name = EXCLUDED.name,
      description = EXCLUDED.description;

-- 3) Upsert subcontrols
INSERT INTO public.subcontrols (id, control_id, name, description)
VALUES
  ('AIS-01', 'AIS', 'Application Security', 'Application security baseline requirements'),
  ('AIS-02', 'AIS', 'Customer Access Requirements', 'Customer access requirements documentation'),
  ('AIS-03', 'AIS', 'Data Integrity', 'Data input and output integrity routines'),
  ('AIS-04', 'AIS', 'Data Security', 'Data security and integrity requirements'),
  ('AAC-01', 'AAC', 'Audit Planning', 'Independent audit program planning'),
  ('AAC-02', 'AAC', 'Independent Audits', 'Independent reviews and assessments'),
  ('AAC-03', 'AAC', 'Information System Regulatory Mapping', 'Regulatory requirements compliance'),
  ('BCR-01', 'BCR', 'Business Continuity Planning', 'Business continuity planning requirements'),
  ('BCR-02', 'BCR', 'Business Continuity Testing', 'Business continuity testing requirements'),
  ('BCR-03', 'BCR', 'Power / Telecommunications', 'Power and telecommunications redundancy'),
  ('CSP-01', 'CSP', 'Resource Provisioning', 'Controls for secure resource provisioning'),
  ('CSP-02', 'CSP', 'Asset Management', 'Management of cloud service assets'),
  ('CSP-03', 'CSP', 'Access Control', 'Access control for cloud services'),
  ('CSP-04', 'CSP', 'Encryption', 'Encryption of cloud service data'),
  ('CUC-01', 'CUC', 'Data Classification', 'Classification of data in cloud services'),
  ('CUC-02', 'CUC', 'Data Protection', 'Protection of data in cloud services'),
  ('CUC-03', 'CUC', 'Access Management', 'Management of access to cloud services'),
  ('SHC-01', 'SHC', 'Incident Management', 'Management of security incidents'),
  ('SHC-02', 'SHC', 'Business Continuity', 'Business continuity management'),
  ('SHC-03', 'SHC', 'Compliance', 'Compliance with requirements'),
  ('SHC-04', 'SHC', 'Audit', 'Audit and assessment'),
  ('CON-01', 'CON', 'Consent Procedures', 'Procedures for obtaining and recording consent'),
  ('CON-02', 'CON', 'Choice Mechanisms', 'Mechanisms for customer choice regarding PII processing'),
  ('CON-03', 'CON', 'Consent Records', 'Maintenance of consent records'),
  ('PUR-01', 'PUR', 'Purpose Specification', 'Specification of PII processing purposes'),
  ('PUR-02', 'PUR', 'Purpose Limitation', 'Limitation of processing to specified purposes'),
  ('PUR-03', 'PUR', 'Purpose Documentation', 'Documentation of processing purposes'),
  ('MIN-01', 'MIN', 'Collection Limitation', 'Limitation of PII collection'),
  ('MIN-02', 'MIN', 'Processing Minimization', 'Minimization of PII processing'),
  ('MIN-03', 'MIN', 'Retention Minimization', 'Minimization of PII retention periods'),
  ('A.5.1', 'A.5', 'A.5.1 Information security policies and procedures', 'Ensure information security policies and procedures are established and maintained'),
  ('A.5.2', 'A.5', 'A.5.2 Information security roles and responsibilities', 'Information security roles and responsibilities shall be defined and allocated'),
  ('A.6.1', 'A.6', 'A.6.1 Internal organization', 'Management framework for information security implementation'),
  ('A.6.2', 'A.6', 'A.6.2 Mobile devices and teleworking', 'Security of mobile devices and teleworking'),
  ('A.7.1', 'A.7', 'A.7.1 Prior to employment', 'Security responsibilities in job descriptions and terms of employment'),
  ('A.7.2', 'A.7', 'A.7.2 During employment', 'Management responsibilities to ensure security awareness'),
  ('A.7.3', 'A.7', 'A.7.3 Termination and change of employment', 'Security aspects of employment termination or change'),
  ('A.8.1', 'A.8', 'A.8.1 Responsibility for assets', 'Inventory and ownership of assets'),
  ('A.8.2', 'A.8', 'A.8.2 Information classification', 'Classification of information according to legal requirements'),
  ('A.8.3', 'A.8', 'A.8.3 Media handling', 'Management of removable media'),
  ('A.9.1', 'A.9', 'A.9.1 Business requirements of access control', 'Access control policy based on business requirements'),
  ('A.9.2', 'A.9', 'A.9.2 User access management', 'User registration and de-registration'),
  ('A.9.3', 'A.9', 'A.9.3 User responsibilities', 'Password use and management'),
  ('A.9.4', 'A.9', 'A.9.4 System and application access control', 'Information access restriction'),
  ('A.10.1', 'A.10', 'A.10.1 Cryptographic controls', 'Policy on the use of cryptographic controls'),
  ('A.10.2', 'A.10', 'A.10.2 Key management', 'Policy on cryptographic key management'),
  ('A.11.1', 'A.11', 'A.11.1 Secure areas', 'Physical security perimeter and controls'),
  ('A.11.2', 'A.11', 'A.11.2 Equipment security', 'Equipment siting, protection, and maintenance'),
  ('A.12.1', 'A.12', 'A.12.1 Operational procedures and responsibilities', 'Documented operating procedures'),
  ('A.12.2', 'A.12', 'A.12.2 Protection from malware', 'Controls against malware'),
  ('A.12.3', 'A.12', 'A.12.3 Backup', 'Backup of information'),
  ('A.12.4', 'A.12', 'A.12.4 Logging and monitoring', 'Event logging and monitoring'),
  ('A.12.5', 'A.12', 'A.12.5 Control of operational software', 'Installation of software on operational systems'),
  ('A.12.6', 'A.12', 'A.12.6 Technical vulnerability management', 'Management of technical vulnerabilities'),
  ('A.13.1', 'A.13', 'A.13.1 Network security management', 'Network controls and security of network services'),
  ('A.13.2', 'A.13', 'A.13.2 Information transfer', 'Policies and procedures for information transfer'),
  ('A.14.1', 'A.14', 'A.14.1 Security requirements of information systems', 'Security requirements analysis and specification'),
  ('A.14.2', 'A.14', 'A.14.2 Security in development and support processes', 'Secure development policy'),
  ('A.14.3', 'A.14', 'A.14.3 Test data', 'Protection of test data'),
  ('A.15.1', 'A.15', 'A.15.1 Information security in supplier relationships', 'Information security policy for supplier relationships'),
  ('A.15.2', 'A.15', 'A.15.2 Supplier service delivery management', 'Monitoring and review of supplier services'),
  ('A.16.1', 'A.16', 'A.16.1 Management of information security incidents', 'Responsibilities and procedures'),
  ('A.17.1', 'A.17', 'A.17.1 Information security continuity', 'Planning information security continuity'),
  ('A.17.2', 'A.17', 'A.17.2 Redundancies', 'Availability of information processing facilities'),
  ('A.18.1', 'A.18', 'A.18.1 Compliance with legal and contractual requirements', 'Identification of applicable legislation'),
  ('A.18.2', 'A.18', 'A.18.2 Information security reviews', 'Independent review of information security'),
  ('A.5.1', 'A.5', 'A.5.1 Information security policies and procedures', 'Ensure information security policies and procedures are established and maintained'),
  ('A.5.2', 'A.5', 'A.5.2 Information security roles and responsibilities', 'Information security roles and responsibilities shall be defined and allocated'),
  ('A.6.1', 'A.6', 'A.6.1 Internal organization', 'Management framework for information security implementation'),
  ('A.6.2', 'A.6', 'A.6.2 Mobile devices and teleworking', 'Security of mobile devices and teleworking'),
  ('A.7.1', 'A.7', 'A.7.1 Prior to employment', 'Security responsibilities in job descriptions and terms of employment'),
  ('A.7.2', 'A.7', 'A.7.2 During employment', 'Management responsibilities to ensure security awareness'),
  ('A.7.3', 'A.7', 'A.7.3 Termination and change of employment', 'Security aspects of employment termination or change'),
  ('A.8.1', 'A.8', 'A.8.1 Responsibility for assets', 'Inventory and ownership of assets'),
  ('A.8.2', 'A.8', 'A.8.2 Information classification', 'Classification of information according to legal requirements'),
  ('A.8.3', 'A.8', 'A.8.3 Media handling', 'Management of removable media'),
  ('A.9.1', 'A.9', 'A.9.1 Business requirements of access control', 'Access control policy based on business requirements'),
  ('A.9.2', 'A.9', 'A.9.2 User access management', 'User registration and de-registration'),
  ('A.9.3', 'A.9', 'A.9.3 User responsibilities', 'Password use and management'),
  ('A.9.4', 'A.9', 'A.9.4 System and application access control', 'Information access restriction'),
  ('A.10.1', 'A.10', 'A.10.1 Cryptographic controls', 'Policy on the use of cryptographic controls'),
  ('A.10.2', 'A.10', 'A.10.2 Key management', 'Policy on cryptographic key management'),
  ('A.11.1', 'A.11', 'A.11.1 Secure areas', 'Physical security perimeter and controls'),
  ('A.11.2', 'A.11', 'A.11.2 Equipment security', 'Equipment siting, protection, and maintenance'),
  ('A.12.1', 'A.12', 'A.12.1 Operational procedures and responsibilities', 'Documented operating procedures'),
  ('A.12.2', 'A.12', 'A.12.2 Protection from malware', 'Controls against malware'),
  ('A.12.3', 'A.12', 'A.12.3 Backup', 'Backup of information'),
  ('A.12.4', 'A.12', 'A.12.4 Logging and monitoring', 'Event logging and monitoring'),
  ('A.12.5', 'A.12', 'A.12.5 Control of operational software', 'Installation of software on operational systems'),
  ('A.12.6', 'A.12', 'A.12.6 Technical vulnerability management', 'Management of technical vulnerabilities'),
  ('A.13.1', 'A.13', 'A.13.1 Network security management', 'Network controls and security of network services'),
  ('A.13.2', 'A.13', 'A.13.2 Information transfer', 'Policies and procedures for information transfer'),
  ('A.14.1', 'A.14', 'A.14.1 Security requirements of information systems', 'Security requirements analysis and specification'),
  ('A.14.2', 'A.14', 'A.14.2 Security in development and support processes', 'Secure development policy'),
  ('A.14.3', 'A.14', 'A.14.3 Test data', 'Protection of test data'),
  ('A.15.1', 'A.15', 'A.15.1 Information security in supplier relationships', 'Information security policy for supplier relationships'),
  ('A.15.2', 'A.15', 'A.15.2 Supplier service delivery management', 'Monitoring and review of supplier services'),
  ('A.16.1', 'A.16', 'A.16.1 Management of information security incidents', 'Responsibilities and procedures'),
  ('A.17.1', 'A.17', 'A.17.1 Information security continuity', 'Planning information security continuity'),
  ('A.17.2', 'A.17', 'A.17.2 Redundancies', 'Availability of information processing facilities'),
  ('A.18.1', 'A.18', 'A.18.1 Compliance with legal and contractual requirements', 'Identification of applicable legislation'),
  ('A.18.2', 'A.18', 'A.18.2 Information security reviews', 'Independent review of information security'),
  ('ART5', 'CH2', 'Article 5 - Principles relating to processing of personal data', 'Lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity and confidentiality'),
  ('ART6', 'CH2', 'Article 6 - Lawfulness of processing', 'Legal bases for processing personal data including consent, contract, legal obligation, vital interests, public interest, legitimate interests'),
  ('ART7', 'CH2', 'Article 7 - Conditions for consent', 'Requirements for valid consent including freely given, specific, informed and unambiguous indication of wishes'),
  ('ART15', 'CH3', 'Article 15 - Right of access', 'Right to obtain confirmation of processing and access to personal data'),
  ('ART16', 'CH3', 'Article 16 - Right to rectification', 'Right to obtain rectification of inaccurate personal data'),
  ('ART17', 'CH3', 'Article 17 - Right to erasure', 'Right to obtain erasure of personal data ("right to be forgotten")'),
  ('ART18', 'CH3', 'Article 18 - Right to restriction of processing', 'Right to restrict the processing of personal data'),
  ('ART20', 'CH3', 'Article 20 - Right to data portability', 'Right to receive personal data and transmit it to another controller'),
  ('ART24', 'CH4', 'Article 24 - Responsibility of the controller', 'Implementation of appropriate technical and organizational measures'),
  ('ART25', 'CH4', 'Article 25 - Data protection by design and by default', 'Implementation of data protection principles and appropriate safeguards'),
  ('ART32', 'CH4', 'Article 32 - Security of processing', 'Implementation of appropriate technical and organizational security measures'),
  ('ART33', 'CH4', 'Article 33 - Notification of personal data breach', 'Notification to supervisory authority of personal data breaches'),
  ('PRV-1', 'PRV', 'Use and Disclosure', 'Requirements for using and disclosing protected health information'),
  ('PRV-2', 'PRV', 'Minimum Necessary', 'Limit use and disclosure of PHI to minimum necessary for intended purpose'),
  ('PRV-3', 'PRV', 'Patient Rights', 'Rights of individuals regarding their health information including access, amendments, and accounting of disclosures'),
  ('PRV-4', 'PRV', 'Notice of Privacy Practices', 'Requirements for informing individuals about privacy practices and their rights'),
  ('PRV-5', 'PRV', 'Business Associates', 'Requirements for agreements with business associates who handle PHI'),
  ('SEC-A', 'SEC', 'Administrative Safeguards', 'Security management, workforce security, information access, training, and evaluation'),
  ('SEC-A1', 'SEC', 'Security Management Process', 'Risk analysis, risk management, sanction policy, and information system activity review'),
  ('SEC-A2', 'SEC', 'Workforce Security', 'Authorization and supervision, workforce clearance, and termination procedures'),
  ('SEC-P', 'SEC', 'Physical Safeguards', 'Facility access, workstation use, and device and media controls'),
  ('SEC-P1', 'SEC', 'Facility Access Controls', 'Contingency operations, facility security plan, access control and validation'),
  ('SEC-P2', 'SEC', 'Workstation and Device Security', 'Proper workstation use and security, and mobile device policies'),
  ('SEC-T', 'SEC', 'Technical Safeguards', 'Access control, audit controls, integrity, authentication, and transmission security'),
  ('SEC-T1', 'SEC', 'Access Control', 'Unique user identification, emergency access, automatic logoff, and encryption'),
  ('SEC-T2', 'SEC', 'Audit Controls', 'Hardware, software, and procedural mechanisms to record and examine activity'),
  ('SEC-T3', 'SEC', 'Transmission Security', 'Technical security measures to guard against unauthorized access to ePHI in transit'),
  ('BRE-1', 'BRE', 'Breach Definition', 'What constitutes a breach of unsecured protected health information'),
  ('BRE-2', 'BRE', 'Risk Assessment', 'Assessment of probability that PHI has been compromised'),
  ('BRE-3', 'BRE', 'Notification to Individuals', 'Requirements for notifying affected individuals of a breach'),
  ('BRE-4', 'BRE', 'Notification to Media', 'Requirements for notifying media of breaches affecting more than 500 residents'),
  ('BRE-5', 'BRE', 'Notification to Secretary', 'Requirements for notifying the Secretary of HHS of breaches'),
  ('ENF-1', 'ENF', 'Compliance Reviews', 'Process for reviewing compliance with HIPAA rules'),
  ('ENF-2', 'ENF', 'Cooperation with Investigations', 'Requirements for cooperating with compliance investigations'),
  ('ENF-3', 'ENF', 'Civil Money Penalties', 'Monetary penalties for violations of HIPAA rules'),
  ('ENF-4', 'ENF', 'Criminal Penalties', 'Criminal penalties for knowing violations of HIPAA rules'),
  ('GOV-1', 'GOV', 'Leadership and Commitment', 'Top management commitment and establishment of AI governance policies'),
  ('GOV-2', 'GOV', 'AI Policy', 'Development and implementation of organizational AI policy'),
  ('GOV-3', 'GOV', 'Roles and Responsibilities', 'Assignment of AI-related roles and responsibilities within the organization'),
  ('GOV-4', 'GOV', 'Resource Management', 'Allocation of resources for AI system development and operation'),
  ('GOV-5', 'GOV', 'Documentation Requirements', 'Maintenance of AI system documentation and records'),
  ('RISK-1', 'RISK', 'Risk Assessment Process', 'Systematic approach to identifying and evaluating AI risks'),
  ('RISK-2', 'RISK', 'Model Risk Management', 'Management of risks associated with AI models and algorithms'),
  ('RISK-3', 'RISK', 'Data Risk Management', 'Management of risks related to training data and input data'),
  ('RISK-4', 'RISK', 'Operational Risk', 'Management of risks in AI system deployment and operation'),
  ('RISK-5', 'RISK', 'Third-Party Risk', 'Management of risks associated with third-party AI components and services'),
  ('RISK-6', 'RISK', 'Monitoring and Review', 'Continuous monitoring and review of AI system risks'),
  ('ETH-1', 'ETH', 'Fairness and Non-discrimination', 'Ensuring AI systems are fair and do not discriminate'),
  ('ETH-2', 'ETH', 'Accountability', 'Clear accountability for AI system decisions and actions'),
  ('ETH-3', 'ETH', 'Human Oversight', 'Maintaining appropriate human oversight of AI systems'),
  ('ETH-4', 'ETH', 'Social Impact Assessment', 'Assessment of AI system impact on society and stakeholders'),
  ('ETH-5', 'ETH', 'Environmental Impact', 'Consideration of environmental impact of AI systems'),
  ('ETH-6', 'ETH', 'Cultural Sensitivity', 'Ensuring AI systems respect cultural differences and values'),
  ('TRA-1', 'TRA', 'System Documentation', 'Documentation of AI system architecture, models, and processes'),
  ('TRA-2', 'TRA', 'Decision Explainability', 'Methods for explaining AI system decisions and recommendations'),
  ('TRA-3', 'TRA', 'Data Transparency', 'Transparency about data sources and data processing'),
  ('TRA-4', 'TRA', 'Performance Metrics', 'Clear reporting of AI system performance and limitations'),
  ('TRA-5', 'TRA', 'User Communication', 'Communication with users about AI system capabilities and limitations'),
  ('TRA-6', 'TRA', 'Incident Reporting', 'Transparent reporting of AI system incidents and issues'),
  ('DEV-1', 'DEV', 'Development Process', 'Structured process for AI system development'),
  ('DEV-2', 'DEV', 'Testing Requirements', 'Comprehensive testing of AI systems before deployment'),
  ('DEV-3', 'DEV', 'Version Control', 'Management of AI system versions and changes'),
  ('DEV-4', 'DEV', 'Quality Assurance', 'Quality assurance processes for AI systems'),
  ('DEV-5', 'DEV', 'Deployment Procedures', 'Procedures for safe deployment of AI systems'),
  ('CC1', 'CC', 'Control Environment', 'Organization demonstrates commitment to integrity and ethical values'),
  ('CC2', 'CC', 'Communication and Information', 'Communication of objectives and responsibilities in internal control'),
  ('CC3', 'CC', 'Risk Assessment', 'Organization specifies objectives and assesses risks to achieving objectives'),
  ('CC4', 'CC', 'Monitoring Activities', 'Organization monitors controls and evaluates results'),
  ('CC5', 'CC', 'Control Activities', 'Organization selects and develops control activities'),
  ('CC6', 'CC', 'Logical and Physical Access', 'Organization implements logical and physical access controls'),
  ('CC7', 'CC', 'System Operations', 'Organization manages system operations and changes'),
  ('CC8', 'CC', 'Change Management', 'Organization implements change management processes'),
  ('CC9', 'CC', 'Risk Mitigation', 'Organization identifies and mitigates risks through business recovery procedures'),
  ('A1.1', 'A', 'Availability Requirements', 'Current processing capacity and system availability requirements'),
  ('A1.2', 'A', 'Capacity Management', 'Infrastructure, software, and data capacity requirements'),
  ('A1.3', 'A', 'Backup and Recovery', 'Data backup, recovery, and business continuity procedures'),
  ('PI1.1', 'PI', 'Processing Objectives', 'System processing objectives, including completeness, accuracy, and timeliness'),
  ('PI1.2', 'PI', 'Input Validation', 'Input data validation and error handling procedures'),
  ('PI1.3', 'PI', 'Processing Validation', 'Processing validation and error handling procedures'),
  ('PI1.4', 'PI', 'Output Validation', 'Output validation and error handling procedures'),
  ('PI1.5', 'PI', 'Processing Authorization', 'System processing authorization procedures'),
  ('C1.1', 'C', 'Confidentiality Requirements', 'Identification of confidential information and handling requirements'),
  ('C1.2', 'C', 'Confidentiality Policies', 'Policies and procedures for protecting confidential information'),
  ('C1.3', 'C', 'Confidentiality Controls', 'Controls to protect confidential information during retention and destruction'),
  ('P1.1', 'P', 'Privacy Notice', 'Communication of privacy policies to data subjects'),
  ('P1.2', 'P', 'Choice and Consent', 'Options for collection, use, and disclosure of personal information'),
  ('P2.1', 'P', 'Collection', 'Collection of personal information is limited to specified purposes'),
  ('P3.1', 'P', 'Use, Retention, Disposal', 'Use of personal information is limited to specified purposes'),
  ('P4.1', 'P', 'Access', 'Data subjects can review and update their personal information'),
  ('P5.1', 'P', 'Disclosure', 'Disclosure of personal information is limited to specified purposes'),
  ('P6.1', 'P', 'Quality', 'Personal information is accurate and complete for specified purposes'),
  ('P7.1', 'P', 'Monitoring and Enforcement', 'Privacy policies and procedures are monitored and enforced'),
  ('GOV.1', 'GOV', 'AI Risk Management Governance', 'Establish organizational governance structure for AI risk management'),
  ('GOV.2', 'GOV', 'AI Policies and Procedures', 'Develop and maintain AI-specific policies and procedures'),
  ('GOV.3', 'GOV', 'AI Risk Culture', 'Foster organizational culture that prioritizes AI risk management'),
  ('GOV.4', 'GOV', 'Stakeholder Engagement', 'Engage with internal and external stakeholders on AI risks'),
  ('GOV.5', 'GOV', 'Resource Allocation', 'Allocate resources for AI risk management activities'),
  ('MAP.1', 'MAP', 'AI System Context', 'Document AI system context, purpose, and intended use'),
  ('MAP.2', 'MAP', 'AI System Capabilities', 'Identify and document AI system capabilities and limitations'),
  ('MAP.3', 'MAP', 'Risk Identification', 'Identify potential risks associated with AI system'),
  ('MAP.4', 'MAP', 'Impact Assessment', 'Assess potential impacts of AI system on stakeholders'),
  ('MAP.5', 'MAP', 'Dependencies', 'Identify and document AI system dependencies'),
  ('MEA.1', 'MEA', 'Risk Analysis', 'Analyze identified risks using appropriate methods'),
  ('MEA.2', 'MEA', 'Risk Assessment', 'Assess likelihood and impact of identified risks'),
  ('MEA.3', 'MEA', 'Risk Metrics', 'Develop and track metrics for AI system risks'),
  ('MEA.4', 'MEA', 'Testing and Validation', 'Test and validate AI system risk controls'),
  ('MEA.5', 'MEA', 'Monitoring', 'Monitor AI system risks and control effectiveness'),
  ('MAN.1', 'MAN', 'Risk Prioritization', 'Prioritize risks based on assessment results'),
  ('MAN.2', 'MAN', 'Risk Response', 'Develop and implement risk response strategies'),
  ('MAN.3', 'MAN', 'Risk Communication', 'Communicate about AI risks to stakeholders'),
  ('MAN.4', 'MAN', 'Documentation', 'Document risk management decisions and actions'),
  ('MAN.5', 'MAN', 'Continuous Improvement', 'Continuously improve AI risk management practices'),
  ('AC-1', 'AC', 'Policy and Procedures', 'Establish and maintain access control policies and procedures.'),
  ('AC-2', 'AC', 'Account Management', 'Manage system accounts, including establishing, activating, modifying, reviewing, disabling, and removing accounts.'),
  ('AC-3', 'AC', 'Access Enforcement', 'Enforce approved authorizations for logical access to information and system resources.'),
  ('AC-4', 'AC', 'Information Flow Enforcement', 'Enforce approved authorizations for controlling the flow of information within the system and between connected systems.'),
  ('AC-5', 'AC', 'Separation of Duties', 'Separate duties of individuals to prevent malicious activities.'),
  ('AC-6', 'AC', 'Least Privilege', 'Employ the principle of least privilege, allowing only authorized accesses necessary to accomplish assigned tasks.'),
  ('AC-7', 'AC', 'Unsuccessful Logon Attempts', 'Enforce limits on unsuccessful logon attempts.'),
  ('AC-8', 'AC', 'System Use Notification', 'Display system use notification message before granting access.'),
  ('AC-9', 'AC', 'Previous Logon Notification', 'Notify user of last successful logon/access.'),
  ('AC-10', 'AC', 'Concurrent Session Control', 'Limit the number of concurrent sessions for each system account.'),
  ('AC-11', 'AC', 'Device Lock', 'Automatically lock session after period of inactivity.'),
  ('AC-12', 'AC', 'Session Termination', 'Automatically terminate user sessions after defined conditions.'),
  ('AC-13', 'AC', 'Supervision and Review — Access Control', 'Supervise and review the activities of users with respect to enforcement of access control.'),
  ('AC-14', 'AC', 'Permitted Actions without Identification or Authentication', 'Identify and document specific user actions that can be performed without identification or authentication.'),
  ('AC-15', 'AC', 'Automated Marking', 'Mark output using standard naming conventions.'),
  ('AC-16', 'AC', 'Security and Privacy Attributes', 'Support and maintain the binding of security and privacy attributes to information in storage, in process, and in transmission.'),
  ('AC-17', 'AC', 'Remote Access', 'Establish and manage remote access to system.'),
  ('AC-18', 'AC', 'Wireless Access', 'Establish configuration requirements and connection requirements for wireless access.'),
  ('AC-19', 'AC', 'Access Control for Mobile Devices', 'Establish usage restrictions and implementation guidance for mobile devices.'),
  ('AC-20', 'AC', 'Use of External Systems', 'Establish terms and conditions for external systems.'),
  ('AC-21', 'AC', 'Information Sharing', 'Enable authorized users to determine whether access authorizations match access restrictions.'),
  ('AC-22', 'AC', 'Publicly Accessible Content', 'Make publicly accessible information available with appropriate restrictions.'),
  ('AC-23', 'AC', 'Data Mining Protection', 'Employ data mining prevention and detection techniques.'),
  ('AC-24', 'AC', 'Access Control Decisions', 'Establish access control decisions based on approved authorizations.'),
  ('AC-25', 'AC', 'Reference Monitor', 'Implement a reference monitor to enforce access control policies.'),
  ('AT-1', 'AT', 'Policy and Procedures', 'Establish security awareness and training policy and procedures.'),
  ('AT-2', 'AT', 'Literacy Training and Awareness', 'Provide security and privacy literacy training to system users.'),
  ('AT-3', 'AT', 'Role-Based Training', 'Provide role-based security and privacy training to personnel with assigned security and privacy roles.'),
  ('AT-4', 'AT', 'Training Records', 'Document and monitor individual information system security and privacy training activities.'),
  ('AT-5', 'AT', 'Training Feedback', 'Provide feedback on organizational training results.'),
  ('AT-6', 'AT', 'Training Environment', 'Provide a realistic training environment that reflects actual system operations.'),
  ('AU-1', 'AU', 'Policy and Procedures', 'Establish audit and accountability policies and procedures.'),
  ('AU-2', 'AU', 'Event Logging', 'Identify the types of events that the system is capable of logging.'),
  ('AU-3', 'AU', 'Content of Audit Records', 'Ensure audit records contain information that establishes what type of event occurred.'),
  ('AU-4', 'AU', 'Audit Storage Capacity', 'Allocate audit record storage capacity and configure auditing.'),
  ('AU-5', 'AU', 'Response to Audit Processing Failures', 'Alert personnel in the event of an audit processing failure.'),
  ('AU-6', 'AU', 'Audit Review, Analysis, and Reporting', 'Review and analyze system audit records for inappropriate or unusual activity.'),
  ('AU-7', 'AU', 'Audit Reduction and Report Generation', 'Provide audit reduction and report generation capability.'),
  ('AU-8', 'AU', 'Time Stamps', 'Use internal system clocks to generate time stamps for audit records.'),
  ('AU-9', 'AU', 'Protection of Audit Information', 'Protect audit information and audit tools from unauthorized access, modification, and deletion.'),
  ('AU-10', 'AU', 'Non-repudiation', 'Provide non-repudiation of actions.'),
  ('AU-11', 'AU', 'Audit Record Retention', 'Retain audit records to provide support for after-the-fact investigations.'),
  ('AU-12', 'AU', 'Audit Generation', 'Provide system capability to generate audit records.'),
  ('AU-13', 'AU', 'Monitoring for Information Disclosure', 'Monitor system for unauthorized disclosure of information.'),
  ('AU-14', 'AU', 'Session Audit', 'Provide capability to capture/record and log user sessions.'),
  ('AU-15', 'AU', 'Alternate Audit Capability', 'Provide alternate audit capability in case of system failure.'),
  ('AU-16', 'AU', 'Cross-Organizational Auditing', 'Employ mechanisms for coordinating audit information among external organizations.'),
  ('CM-1', 'CM', 'Policy and Procedures', 'Establish and maintain configuration management policies and procedures.'),
  ('CM-2', 'CM', 'Baseline Configuration', 'Develop, document, and maintain baseline configurations of organizational systems.'),
  ('CM-3', 'CM', 'Configuration Change Control', 'Track and control changes to the system configuration.'),
  ('CM-4', 'CM', 'Security Impact Analysis', 'Analyze changes to the system to determine potential security impacts prior to change implementation.'),
  ('CM-5', 'CM', 'Access Restrictions for Change', 'Define, document, approve, and enforce physical and logical access restrictions for changes to the system.'),
  ('CM-6', 'CM', 'Configuration Settings', 'Establish and document configuration settings for components employed within the system.'),
  ('CM-7', 'CM', 'Least Functionality', 'Configure the system to provide only essential capabilities.'),
  ('CM-8', 'CM', 'System Component Inventory', 'Develop and document an inventory of system components.'),
  ('CM-9', 'CM', 'Configuration Management Plan', 'Develop, document, and implement a configuration management plan for the system.'),
  ('CM-10', 'CM', 'Software Usage Restrictions', 'Use software and associated documentation in accordance with contract agreements and copyright laws.'),
  ('CM-11', 'CM', 'User-Installed Software', 'Establish policies governing the installation of software by users.'),
  ('CM-12', 'CM', 'Information Location', 'Track the location of system components.'),
  ('CM-13', 'CM', 'Data Action Mapping', 'Develop and document a map of system data actions.'),
  ('CM-14', 'CM', 'Signed Components', 'Prevent the installation of software and firmware components without verification of the component signatures.'),
  ('CP-1', 'CP', 'Policy and Procedures', 'Develop, document, and disseminate contingency planning policy and procedures.'),
  ('CP-2', 'CP', 'Contingency Plan', 'Develop and maintain a contingency plan for the system.'),
  ('CP-3', 'CP', 'Contingency Training', 'Train personnel in their contingency roles and responsibilities.'),
  ('CP-4', 'CP', 'Contingency Plan Testing', 'Test the contingency plan to determine effectiveness and readiness.'),
  ('CP-5', 'CP', 'Contingency Plan Update', 'Review and update the contingency plan to address changes or problems.'),
  ('CP-6', 'CP', 'Alternate Storage Site', 'Establish an alternate storage site including necessary agreements.'),
  ('CP-7', 'CP', 'Alternate Processing Site', 'Establish an alternate processing site including necessary agreements.'),
  ('CP-8', 'CP', 'Telecommunications Services', 'Establish alternate telecommunications services including necessary agreements.'),
  ('CP-9', 'CP', 'System Backup', 'Conduct system backups and protect backup information.'),
  ('CP-10', 'CP', 'System Recovery and Reconstitution', 'Provide for recovery and reconstitution of the system to a known state.'),
  ('CP-11', 'CP', 'Alternate Communications Protocols', 'Provide the capability to employ alternative communications protocols.'),
  ('CP-12', 'CP', 'Safe Mode', 'Implement a safe mode of operation for the system.'),
  ('CP-13', 'CP', 'Alternative Security Mechanisms', 'Employ alternative or supplemental security mechanisms when primary means of implementing a security function is unavailable.'),
  ('REQ1.1', 'REQ1', 'Network Security Controls', 'Network security controls (NSCs) are defined and implemented'),
  ('REQ1.2', 'REQ1', 'Network Configuration Standards', 'Configuration standards for NSC are defined and implemented'),
  ('REQ1.3', 'REQ1', 'Network Access', 'Network access to and from the cardholder data environment is restricted'),
  ('REQ2.1', 'REQ2', 'Security Configuration Standards', 'Security configuration standards are developed and maintained'),
  ('REQ2.2', 'REQ2', 'Vendor Defaults', 'Vendor-supplied defaults are changed and unnecessary accounts are removed'),
  ('REQ3.1', 'REQ3', 'Data Retention', 'Keep cardholder data storage to a minimum'),
  ('REQ3.2', 'REQ3', 'Sensitive Authentication Data', 'Do not store sensitive authentication data after authorization'),
  ('REQ3.3', 'REQ3', 'Display of PAN', 'Mask PAN when displayed'),
  ('REQ4.1', 'REQ4', 'Data Transmission', 'Use strong cryptography and security protocols'),
  ('REQ4.2', 'REQ4', 'PAN Transmission', 'Never send unprotected PANs by end-user messaging technologies'),
  ('REQ5.1', 'REQ5', 'Anti-Malware Deployment', 'Deploy anti-malware mechanisms'),
  ('REQ5.2', 'REQ5', 'Anti-Malware Updates', 'Keep anti-malware mechanisms current'),
  ('REQ5.3', 'REQ5', 'Anti-Malware Process', 'Anti-malware mechanisms are actively running'),
  ('REQ6.1', 'REQ6', 'Security Vulnerabilities', 'Identify security vulnerabilities'),
  ('REQ6.2', 'REQ6', 'Software Updates', 'Protect system components and software from known vulnerabilities'),
  ('REQ6.3', 'REQ6', 'Software Development', 'Develop secure software applications')
ON CONFLICT (id) DO UPDATE
  SET control_id = EXCLUDED.control_id,
      name = EXCLUDED.name,
      description = EXCLUDED.description;
